Script started on 2025-11-21 15:22:36-05:00 [TERM="screen-256color" TTY="/dev/pts/72" COLUMNS="159" LINES="42"]
Starting chat with profile: default
[0m[?7h[0mInitializing agent 'default'...
[0m[0m[?7h[0;38;5;28;1mReady! Type 'exit' to quit.[0m
[0m[6n[?2004h[?1l[?25l[0m[?7l[0m[J[0;1m>[2C[?7h[0m[?12l[?25h[?25l[?7l[?7h[0m[?12l[?25h[?25l[?7l[0mh[?7h[0m[?12l[?25h[?25l[?7l[0mi[?7h[0m[?12l[?25h[?25l[?7l[0m![?7h[0m[?12l[?25h[?25l[?7l[C[?7h[0m[?12l[?25h[?25l[?7l[0mh[?7h[0m[?12l[?25h[?25l[?7l[0mo[?7h[0m[?12l[?25h[?25l[?7l[0mw[?7h[0m[?12l[?25h[?25l[?7l[C[?7h[0m[?12l[?25h[?25l[?7l[0ma[?7h[0m[?12l[?25h[?25l[?7l[0mr[?7h[0m[?12l[?25h[?25l[?7l[0me[?7h[0m[?12l[?25h[?25l[?7l[C[?7h[0m[?12l[?25h[?25l[?7l[0my[?7h[0m[?12l[?25h[?25l[?7l[0mo[?7h[0m[?12l[?25h[?25l[?7l[0mu[?7h[0m[?12l[?25h[?25l[?7l[0m?[?7h[0m[?12l[?25h[?25l[?7l[18D[0m[J[0;1m> [0mhi! how are you?[18D[0m
[J[?7h[0m[?12l[?25h[?2004l[0m[?7h[0;38;5;116mThinking...[0m
[0m[?7hHello[?7h![?7h I'm just[?7h a computer program,[?7h so[?7h I[?7h don't have[?7h feelings,[?7h but I'm[?7h here and[?7h ready to[?7h help you[?7h. How[?7h can I[?7h assist you[?7h today[?7h?[?7h
[6n[?2004h[?25l[0m[?7l[0m[J[0;1m>[2C[?7h[0m[?12l[?25h[?25l[?7l[?7h[0m[?12l[?25h[?25l[?7l[2D[0m[J[0;38;5;102;1m> [0;38;5;102m                                                                                                                                                            [158C [0m
[J[?7h[0m[?12l[?25h[?2004l
Script done on 2025-11-21 15:22:45-05:00 [COMMAND_EXIT_CODE="0"]
